### PR TITLE
Retexture Teckle [WIP]

### PR DESCRIPTION
**Pull request by adrwa**
WIP PR to retexture the mod

- [x] Filter
- [x] Sorting Machine
- [x] Transposer
- [x] Alloy Furnace
- [x] Retriever
- [x] Fabricator
- [x] Beam Quarry
- [x] Block Breaker
- [ ] Tube
- [x] Nikolite Ore
- [ ] Paintbrush
- [x] Red & Blue Alloy Ingots, Blocks & Wafers
- [x] Silicon Wafer
- [x] Brass Ingot
- [ ] Preciso™ Blade
- [x] Silicon Boule

### CODE REVIEW

**Comment by darkevilmac** [comment]
Nice, only thing I'm not really a fan of is the red/blue ingots and wafers. The colours are a bit too muted in my opinion.

EDIT: Missed one other thing, I know the alloy furnace looked silly but that was somewhat intentional. If you can try and reincorporate the original 'face' into the new design that would be preferred.

**Comment by adrwa** [comment]
I agree with the red/blue ingots and wafers, even the blocks, they're really the only things i dont like all that much and i've been trying to make them better

**Comment by dblsaiko** [comment]
You can use mine if you want (or modify them, or whatever). 
[silicon wafer](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/resources/assets/quacklib/textures/items/component/17.png)
[red silicon wafer](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/resources/assets/quacklib/textures/items/component/18.png)
[blue silicon wafer](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/resources/assets/quacklib/textures/items/component/19.png)
[red ingot](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/resources/assets/quacklib/textures/items/component/20.png)
[blue ingot](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/resources/assets/quacklib/textures/items/component/21.png)

edit: Ah, I see you've ninja'd me with the ingot textures :P

**Comment by adrwa** [comment]
These are currently what i've changed them to,

**Pull request merged**
